GET http://localhost:3000/

###
# Login details for server at 4000
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "kyle",
    "password": "password123"
}

###
# Login details for server at 4000 for joe
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "joe",
    "password": "password123"
}

### 
# With the access token access the projects at /projects/me, access token
GET http://localhost:3000/projects/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImpvZSIsImlhdCI6MTc2OTc4MjQyOSwiZXhwIjoxNzY5NzgyNDg5fQ.H3xX_aFpro3nSberu4LnhtN8a0sfd8S7uVEnLyftDQg

### 
# With the access token access the projects at /projects, access token
GET http://localhost:3000/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImpvZSIsImlhdCI6MTc2OTc4MjQyOSwiZXhwIjoxNzY5NzgyNDg5fQ.H3xX_aFpro3nSberu4LnhtN8a0sfd8S7uVEnLyftDQg

###
# If token expire goto /token for new one, here refresh token
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJqb2UiLCJwYXNzd29yZCI6IiQyYiQxMCRVOGNpMTlwWllxUDJ2RzNuOVI2MlRlb3V4OGRDTm13YW50WHpwVnBUZjdpLlpHMXk2UUNmYSIsImlhdCI6MTc2OTc4MjM2NX0.GC300UbCvlc0ltQYph3Wyy4ANduTVZqEs9-d99zVmio"
}

###
# If logout token here is refresh token
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJreWxlIiwicGFzc3dvcmQiOiIkMmIkMTAkTGRISGpUVVNKM2pONC8yMndCUkhPT1FyZXMuTHRvSHAuMlNLb3p3aVFJbWRpbmNNNldNc08iLCJpYXQiOjE3Njk3ODAzMjV9.Z06J9XqRADk0Ox608qcaXc2Jx9G0rq20tHOPOTLyQd8"
}

###
# Accessing the admin page
GET http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImpvZSIsImlhdCI6MTc2OTc4MjQyOSwiZXhwIjoxNzY5NzgyNDg5fQ.H3xX_aFpro3nSberu4LnhtN8a0sfd8S7uVEnLyftDQg

